# Generated by Django 3.0.6 on 2020-05-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='en_stock',
            field=models.DecimalField(decimal_places=2, max_digits=4, max_length=4),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=4, max_length=4),
        ),
    ]
