# Generated by Django 3.0.6 on 2020-05-22 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_auto_20200522_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ManyToManyField(blank=True, null=True, related_name='get_categorias', to='producto.Categoria', verbose_name='categorias'),
        ),
    ]
