# Generated by Django 3.0.6 on 2020-05-24 16:34

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_auto_20200520_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='estado',
            field=django_fsm.FSMField(default='creada', max_length=50, protected=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='codigo',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=4, max_length=4, null=True),
        ),
    ]
