# Generated by Django 3.0.6 on 2020-05-24 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0004_auto_20200524_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='codigo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
