# Generated by Django 3.0.6 on 2020-05-25 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0007_auto_20200524_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10, max_length=4, null=True),
        ),
    ]
