# Generated by Django 3.0.6 on 2020-05-25 20:32

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0008_auto_20200524_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=django_fsm.FSMIntegerField(choices=[(0, 'creada'), (1, 'pagada'), (2, 'facturada'), (3, 'finalizada'), (4, 'cancelada'), (5, 'anulada')], default='creada', protected=True),
        ),
    ]
